!!com.example.app.properties.PropertiesData
appiumProperties:
  platformName: android
  deviceName: device
  udid: R9RRC01TP8L
  app: C:\Users\ACER\Appium-Server-GUI-windows-1.22.3-4\app-debug_v.1.0.apk
  automationName: UIAutomator2
  newCommandTimeout: 120
  autoGrantPermissions: true
